import { chromium } from '@playwright/test';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--autoplay-policy=no-user-gesture-required']});
const pg=await b.newPage({viewport:{width:1440,height:900}});
await pg.route('**fonts.g**',r=>r.abort());
await pg.goto('file:///tmp/claude-0/-home-user-ui-ux-pro-max-skill/a2f32733-7919-5e73-a972-f964cf818630/scratchpad/milaedia-site.html');
await pg.waitForTimeout(900);
await pg.evaluate(()=>window.postMessage({t:'nav',p:'/home'},'*')); await pg.waitForTimeout(1200);
const F=pg.frames()[1];
await F.evaluate(()=>document.querySelector('[data-atelier]')?.scrollIntoView({block:'center'}));
await pg.waitForTimeout(3500);
const v = await F.evaluate(()=>{const v=document.querySelector('[data-atelier-video]');return v?{src:(v.getAttribute('src')||'(none)').slice(0,42),w:v.videoWidth,h:v.videoHeight,t:+v.currentTime.toFixed(2),paused:v.paused,ready:v.readyState}:'no element';});
console.log('atelier video:', v);
console.log('depth planes:', await F.evaluate(()=>document.querySelectorAll('[data-depth]').length));
await b.close();
